services:
    pgvector:
        image: 'pgvector/pgvector:pg16'
        environment:
            - 'POSTGRES_DB=client-support-db'
            - 'POSTGRES_PASSWORD=password'
            - 'POSTGRES_USER=user'
        labels:
            - "org.springframework.boot.service-connection=postgres"
        ports:
            - '5432'
